---
name: Data-Pareto
version: 0.04
author:
  - 'Przemyslaw Wesolek <jest@go.art.pl>'
abstract: Computing Pareto sets in Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Scalar::Util: 0
build_requires:
  Test::More: 0
provides:
  Data::Pareto:
    file: lib/Data/Pareto.pm
    version: 0.04
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
