---
name: Data-Pareto
version: 0.05
author:
  - 'Przemyslaw Wesolek <jest@go.art.pl>'
abstract: Computing Pareto sets in Perl
license: artistic_2
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-Pareto
  repository: http://github.com/jest/perl.mod.Data-Pareto
requires:
  Carp: 0
  Scalar::Util: 0
build_requires:
  Test::More: 0
provides:
  Data::Pareto:
    file: lib/Data/Pareto.pm
    version: 0.05
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
